# Generated by Django 6.0 on 2025-12-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_absence_justification'),
        ('attendance', '0003_alter_user_username'),
    ]

    operations = [
    ]
